name = "Refal5 Syntax Highlighting"
version = "0.2.1"
authors = ["Mikhail Butvin <butvin.mihail@yandex.ru>"]
description = "Refal5 Syntax Highlighting"
repository = "https://github.com/butvinm/zed-refal5"
id = "refal5"
schema_version = 1

[grammars.refal5]
repository = "https://github.com/butvinm/tree-sitter-refal5"
commit = "e7d4eb4c8e63ada1a0f01b4a03c3204a0b5ade92"
