name = "Refal5 Syntax Highlighting"
version = "0.2.2"
authors = ["Mikhail Butvin <butvin.mikhail@gmail.com>"]
description = "Refal5 Syntax Highlighting"
repository = "https://github.com/butvinm/zed-refal5"
id = "refal5"
schema_version = 1

[grammars.refal5]
repository = "https://github.com/butvinm/tree-sitter-refal5"
commit = "7c139a4225c9500b32ba00b17f4683140906259c"
