name = "Refal5 Syntax Highlighting"
version = "0.2.2"
authors = ["Mikhail Butvin <butvin.mihail@yandex.ru>"]
description = "Refal5 Syntax Highlighting"
repository = "https://github.com/butvinm/zed-refal5"
id = "refal5"
schema_version = 1

[grammars.refal5]
repository = "https://github.com/butvinm/tree-sitter-refal5"
commit = "bd3c945c29d057dd6808a7072c28bb9aa8b0dc53"
